#!/bin/bash

#Shell script to run the executable angcorr_main from /bin/ directory and plot the results from angcorr_main.cpp and angcorr_ggg.cpp using gnuplot

#command rm angcorr.plt
#command rm a2a4.plt
#command rm angcorr.pdf
#command rm a2a4.pdf
#command rm angcorr.dat
#command rm angcorr_pure.dat

#command rm 1--3_angcorr.plt
#command rm 1--3_angcorr.pdf
#command rm 1--3_angcorr.dat
#command rm 1--3_angcorr_pure.dat

#path of 'angcorr_main'
command bin/main

#command tail -20 angcorr.dat |head -1 |cut -b 18-30

#creating a angcorr.plt to plot the results from 1--2 angular correlation 
echo "#set terminal to print to a pdf">>angcorr.plt
echo "set terminal postscript enhanced color \"Times-Roman, 20\"">>angcorr.plt
echo "set output '| ps2pdf - angcorr.pdf'">>angcorr.plt

echo "#set axis range, labels, plot title and its position">>angcorr.plt
echo "set xlabel 'Angle'">>angcorr.plt
echo "set ylabel 'W2'">>angcorr.plt
echo "set key top right">>angcorr.plt
#echo "set yrange [0.5:1.5]">>angcorr.plt
#echo "set xrange [0.:180.]">>angcorr.plt

echo "#Plotting data">>angcorr.plt
echo "#set label 1 'Mean = 0' at 3.4 , 550.">>angcorr.plt
echo "#set label 2 'Standard Deviation = 2' at 3.4 , 500">>angcorr.plt
echo "plot 'angcorr.dat' using 1:2 lt -4 pt 7 lc rgb \"red\" tit 'Angular Correlation">>angcorr.plt
echo "replot 'angcorr_pure.dat' using 1:2 lt -4 pt 7 lc rgb \"blue\" tit 'Angular Correlation for Pure transition">>angcorr.plt

command gnuplot angcorr.plt

#creating a a2a4.plt to plot the a2 vs. a4 values
echo "#set terminal to print to a pdf">>a2a4.plt
echo "set terminal postscript enhanced color \"Times-Roman, 20\"">>a2a4.plt
echo "set output '| ps2pdf - a2a4.pdf'">>a2a4.plt

echo "#set axis range, labels, plot title and its position">>a2a4.plt
echo "set xlabel 'a2'">>a2a4.plt
echo "set ylabel 'a4'">>a2a4.plt
echo "set key top right">>a2a4.plt

echo "#Plotting data">>a2a4.plt

echo "plot 'a2a4.dat' with lines lw 5 title 'A4 vs A2', 'coefficients.dat' using 1:2 lt -4 pt 5 lc rgb \"red\" ps 2 tit 'Calculated Value">>a2a4.plt

command gnuplot a2a4.plt

#creating a 1--3_angcorr.plt to plot the results from 1--3 directional angular correlation
echo "#set terminal to print to a pdf">>1--3_angcorr.plt
echo "set terminal postscript enhanced color \"Times-Roman, 20\"">>1--3_angcorr.plt
echo "set output '| ps2pdf - 1--3_angcorr.pdf'">>1--3_angcorr.plt

echo "#set axis range, labels, plot title and its position">>1--3_angcorr.plt
echo "set xlabel 'Angle'">>1--3_angcorr.plt
echo "set ylabel 'W2'">>1--3_angcorr.plt
echo "set key top right">>1--3_angcorr.plt

echo "#Plotting data">>1--3_angcorr.plt
echo "#set label 1 'Mean = 0' at 3.4 , 550.">>1--3_angcorr.plt
echo "#set label 2 'Standard Deviation = 2' at 3.4 , 500">>1--3_angcorr.plt
echo "plot '1--3_angcorr.dat' using 1:2 lt -4 pt 7 lc rgb \"red\" tit 'Angular Correlation">>1--3_angcorr.plt
echo "replot '1--3_angcorr_pure.dat' using 1:2 lt -4 pt 7 lc rgb \"blue\" tit 'Angular Correlation for Pure transition">>1--3_angcorr.plt

command gnuplot 1--3_angcorr.plt

command echo "Plots created in pdf files!"
